Add solution for Accordion
js-tasks-ru/htmlcss-20230911-4_anton-zykov pull request #6
Opened 2023-09-20 14:54 UTC by anton-zykov

2023-09-20 14:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-20 20:12 UTC, GSemikozov requested changes

2023-09-20 20:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import '../../assets/fonts/fonts.css';
см ПР с кнопками

2023-09-20 20:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
лишнее

2023-09-22 13:21 UTC, GSemikozov requested changes

2023-09-22 13:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import '../../assets/css/main.css';
не надо, наоборот - в main подключаем компоненты)

2023-09-22 14:34 UTC, anton-zykov commented on 03-lection1/02-accordion/accordion.css
> +@import '../../assets/css/main.css';
Всё, сложилась в голове картинка )

2023-09-22 14:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-22 15:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-24 21:31 UTC, GSemikozov approved these changes

2023-09-24 21:31 UTC, merged